# **La creation du fichier ventes dirty CSV**

In [41]:
import random
import csv

random.seed(42)

header = ["ID", "Prix", "Quantite", "Remise"]
rows = []

for i in range(500):
    row_id = 500 + i
    
    # Prix : manquant, virgule française, avec €, négatif, ou normal
    r = random.random()
    if r < 0.05:
        prix = ""
    elif r < 0.10:
        prix = str(round(random.uniform(5, 200), 2)).replace(".", ",")
    elif r < 0.13:
        prix = f"{round(random.uniform(5, 200), 2)} €"
    elif r < 0.15:
        prix = f"-{round(random.uniform(5, 50), 2)}"
    else:
        prix = round(random.uniform(5, 200), 2)
    
    # Quantite : manquant, zéro, en lettres, outlier, ou normal
    r = random.random()
    if r < 0.04:
        quantite = ""
    elif r < 0.07:
        quantite = 0
    elif r < 0.10:
        quantite = random.choice(["un", "deux", "trois", "cinq"])
    elif r < 0.12:
        quantite = random.randint(100, 500)
    else:
        quantite = random.randint(1, 15)
    
    # Remise : manquante, avec %, hors plage, négative, ou normale
    r = random.random()
    if r < 0.08:
        remise = ""
    elif r < 0.12:
        remise = f"{random.randint(0, 50)}#"
    elif r < 0.14:
        remise = random.randint(101, 150)
    elif r < 0.16:
        remise = -random.randint(1, 10)
    else:
        remise = random.choice([0, 0, 0, 5, 5, 10, 10, 15, 20, 25, 30])
    
    rows.append([row_id, prix, quantite, remise])

# Injecter des IDs dupliqués
rows[30][0] = rows[10][0]
rows[75][0] = rows[22][0]

with open("ventes.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(rows)

print("Fichier ventes.csv créé avec 100 lignes de données sales.")

Fichier ventes.csv créé avec 100 lignes de données sales.

# **Nettoyage du dataset**

**Chargement & inspection**

In [42]:
import pandas as pd
import numpy as np

df = pd.read_csv('ventes.csv')
print(df.shape)
df.head(10)

(500, 4)

    ID     Prix Quantite Remise
0  500     9.88        4    107
1  501   178.98     cinq    NaN
2  502    50,37        9     30
3  503    86.81        5      0
4  504    36.13        5     -6
5  505  79.09 €        6      0
6  506   109.56        7    NaN
7  507   127.58        6      0
8  508      NaN        5      5
9  509    79.12       14     10

**Info & valeurs manquantes**

In [43]:
df.info()
print('\nNaN par colonne:')
print(df.isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        500 non-null    int64
 1   Prix      480 non-null    str
 2   Quantite  486 non-null    str
 3   Remise    458 non-null    str
dtypes: int64(1), str(3)
memory usage: 15.8 KB

NaN par colonne:
ID           0
Prix        20
Quantite    14
Remise      42
dtype: int64

**Reperer les valeurs suspects**

In [44]:
for col in ['Prix', 'Quantite', 'Remise']:
    print(f'--- {col} ---')
    print(df[col].astype(str).unique()[:15])
    print()

--- Prix ---
<StringArray>
[   '9.88',  '178.98',   '50,37',   '86.81',   '36.13', '79.09 €',  '109.56',
  '127.58',       nan,   '79.12',  '135.68',  '109.16',   '47.82',  '161.98',
   '66.36']
Length: 15, dtype: str

--- Quantite ---
<StringArray>
[   '4', 'cinq',    '9',    '5',    '6',    '7',   '14',   '11',    '8',
   '13',    '2',    '3',   '10',    '0',    nan]
Length: 15, dtype: str

--- Remise ---
<StringArray>
['107',   nan,  '30',   '0',  '-6',   '5',  '10',  '25',  '20', '42#',  '15',
 '27#',  '1#',  '-1',  '-3']
Length: 15, dtype: str

**Nettoyer Prix**

In [45]:
df_clean = df.copy()

df_clean['Prix'] = (
    df_clean['Prix'].astype(str)
    .str.replace('€', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip()
)
df_clean['Prix'] = pd.to_numeric(df_clean['Prix'], errors='coerce')
df_clean.loc[df_clean['Prix'] < 0, 'Prix'] = df_clean['Prix'].abs()

**Nettoyer Quantite**

In [46]:
mots_vers_int = {'un': 1, 'deux': 2, 'trois': 3, 'quatre': 4, 'cinq': 5}

df_clean['Quantite'] = (
    df_clean['Quantite'].astype(str).str.strip().str.lower()
    .replace(mots_vers_int)
)
df_clean['Quantite'] = pd.to_numeric(df_clean['Quantite'], errors='coerce')

**Nettoyer Remise**

In [47]:
df_clean['Remise'] = (
    df_clean['Remise'].astype(str)
    .str.replace('%', '', regex=False)
    .str.strip()
)
df_clean['Remise'] = pd.to_numeric(df_clean['Remise'], errors='coerce')
df_clean.loc[(df_clean['Remise'] < 0) | (df_clean['Remise'] > 100), 'Remise'] = np.nan

**Doublons**

In [48]:
print('IDs dupliqués :')
print(df_clean[df_clean.duplicated('ID', keep=False)].sort_values('ID'))

df_clean = df_clean.drop_duplicates('ID', keep='first').reset_index(drop=True)

IDs dupliqués :
     ID    Prix  Quantite  Remise
10  510  135.68      11.0    25.0
30  510  119.75       NaN     0.0
22  522  103.99       6.0    20.0
75  522  181.05       5.0     0.0

**Imputation**

In [49]:
df_clean['Prix'] = df_clean['Prix'].fillna(df_clean['Prix'].median())
df_clean['Quantite'] = df_clean['Quantite'].fillna(df_clean['Quantite'].median()).astype(int)
df_clean['Remise'] = df_clean['Remise'].fillna(0)

df_clean.info()
df_clean.describe()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        498 non-null    int64
 1   Prix      498 non-null    float64
 2   Quantite  498 non-null    int64
 3   Remise    498 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 15.7 KB

               ID        Prix    Quantite      Remise
count  498.000000  498.000000  498.000000  498.000000
mean   750.291165  104.168112   12.807229    9.769076
std    144.222628   55.088826   39.947035   10.065024
min    500.000000    5.220000    0.000000    0.000000
25%    626.250000   57.327500    4.000000    0.000000
50%    750.500000  105.195000    8.000000    5.000000
75%    874.750000  151.465000   12.000000   20.000000
max    999.000000  199.860000  495.000000   30.000000

**Export simple**

In [50]:
df_clean.to_csv('ventes_clean.csv', index=False)
print('Export OK :', df_clean.shape)
df_clean.head()

Export OK : (498, 4)

    ID    Prix  Quantite  Remise
0  500    9.88         4     0.0
1  501  178.98         5     0.0
2  502   50.37         9    30.0
3  503   86.81         5     0.0
4  504   36.13         5     0.0